version: "3.8"
name: bigdata

services:
  postgresql:
    image: postgres:16.10
    environment:
      POSTGRES_USER: BIGDATA
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  grafana:
    image: grafana/grafana:10.0.0
    container_name: hf_grafana
    depends_on:
      - postgresql
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_PROVISIONING_PATH: /etc/grafana/provisioning
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped

volumes:
  postgres_data:
