apiVersion: 1

datasources:
  - name: HFDB
    type: postgres
    access: proxy
    url: localhost:5432
    database: postgres
    user: BIGDATA
    password: PASSWORD
    isDefault: true
    editable: true
