{
 "title": "Аналитика датасета Hugging Face Models",
 "time": { "from": "2022-03-01T00:00:00.000Z", "to": "2025-11-01T00:00:00.000Z" },
 "panels": [
  {
   "title": "Топ авторов",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * FROM hf_leaders LIMIT 50 "
    }
   ]
  },
  {
   "title": "Динамика активности скачиваний моделей",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * FROM hf_downloads LIMIT 50 "
    }
   ]
  },
  {
   "title": "Количество моделей по областям использования",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 11, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT * FROM hf_pipeline_tag LIMIT 50 "
    }
   ]
  },
  {
   "title": "Динамика использования лицензий",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT * FROM hf_license LIMIT 50 "
    }
   ]
  },
  {
   "title": "Доля моделей по использованию современных архитектур",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT * FROM hf_architecture LIMIT 50 "
    }
   ]
  }
 ]
}